### ISSUE TITLE
Format exception

### ISSUE THREAD

**Issue by belg4mit** [marcieldeg/access2excel#1]
This program looks like it would do exactly what I am looking for, but unfortunately I get the following error:

Exception in thread "main" java.io.IOException: file format [V1997 [VERSION_3]] does not support writing for Trane.mdb
        at com.healthmarketscience.jackcess.impl.DatabaseImpl.open(DatabaseImpl.java:392)
        at com.healthmarketscience.jackcess.DatabaseBuilder.open(DatabaseBuilder.java:252)
        at com.healthmarketscience.jackcess.DatabaseBuilder.open(DatabaseBuilder.java:291)
        at br.com.degasperi.access2excel.Access2Excel.open(Access2Excel.java:40)
        at br.com.degasperi.access2excel.Access2Excel.open(Access2Excel.java:44)
        at br.com.degasperi.access2excel.Access2Excel.main(Access2Excel.java:182)
        Suppressed: java.lang.NullPointerException
                at br.com.degasperi.access2excel.Access2Excel.close(Access2Excel.java:171)
                at br.com.degasperi.access2excel.Access2Excel.main(Access2Excel.java:184)

**Comment by marcieldeg** [comment]
Can you send me your mdb file?

**Comment by marcieldeg** [comment]
You can try this, for Windows:
https://sourceforge.net/projects/mdbadmin/

**Comment by belg4mit** [comment]
The documentation should be clearer about the limitations then. There is less of a need for such a tool for modern Access (if one has Office), than there is for the older format that are no longer supported in Redmon's own software. I'm aware of MDBAdmin, but I need to bulk convert files. I've ended up using [https://sourceforge.net/projects/accessconverter/](https://sourceforge.net/projects/accessconverter/) although it creates very large files which require further processing. Perhaps you could hook into a copy of that for older MDB files.

**Comment by marcieldeg** [comment]
Fixed.
